### ISSUE TITLE
Service Container Linter broken with any `MapperBuilderConfiguratorAttribute`

### ISSUE THREAD

**Issue by ddebin** [CuyZ/Valinor-Bundle#13]
When using `MapperBuilderConfiguratorAttribute` (`AllowPermissiveTypes`, `AllowSuperfluousKeys`, ...) with Mapper injection, service container linting (`bin/console lint:container`) is broken with `RuntimeException` "Invalid service ...: the class is not set.".

Works fine if you omit the attribute.

**Comment by romm** [comment]
Hi @ddebin, thanks for the report, this should be fixed by #14.
