### ISSUE TITLE
Does cache warmup really fork for classes?

### ISSUE THREAD

**Issue by simPod** [CuyZ/Valinor-Bundle#2]
Since the tag works only for services, I don't see how this could work.

We cannot register `ClassThatWillBeWarmedUp` as a service without specifying values for its scalar arguments. Which we don't want to do since Valinor passes values there, not container.

<img width="925" alt="image" src="https://github.com/CuyZ/Valinor-Bundle/assets/327717/683e80da-bcbd-4fb8-980c-2d876e8cb4dc">

**Comment by romm** [comment]
Hi @simPod I ran into a similar issue as the one you described here. I've submitted #4 which should make it easier to use the attribute.
